export const sellerProducts = [
    // Electronics
    {
      id: 1,
      name: "Wireless Headphones",
      description: "High-quality wireless headphones with noise cancellation.",
      quantity: "25",
      location: "New York, USA",
      image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6373/6373460_sd.jpg?format=webp",
      price: "199.99",
      category: "electronics",
    },
    {
      id: 2,
      name: "Smartphone",
      description: "Latest smartphone with advanced features and sleek design.",
      quantity: "50",
      location: "San Francisco, USA",
      image: "https://mobileleb.com/cdn/shop/files/apple-mobile-phone-apple-iphone-15-128gb-33291194957956_1200x1200.jpg?v=1694765742",
      price: "699.99",
      category: "electronics",
    },
    {
      id: 3,
      name: "Laptop",
      description: "Lightweight and powerful laptop for professionals.",
      quantity: "15",
      location: "Los Angeles, USA",
      image: "https://m.media-amazon.com/images/I/51K8mRLCTdL.jpg",
      price: "999.99",
      category: "electronics",
    },
    {
      id: 4,
      name: "Gaming Console",
      description: "Next-generation gaming console for immersive gaming.",
      quantity: "30",
      location: "Seattle, USA",
      image: "https://media.philstar.com/photos/2024/09/11/ps5-pro_2024-09-11_12-26-11.jpg",
      price: "399.99",
      category: "electronics",
    },
  
    // Furniture
    {
      id: 5,
      name: "Wooden Table",
      description: "Durable wooden table perfect for dining or work.",
      quantity: "20",
      location: "Austin, USA",
      image: "https://i.etsystatic.com/29779188/r/il/59b0f4/6237906278/il_fullxfull.6237906278_kon9.jpg",
      price: "149.99",
      category: "furniture",
    },
    {
      id: 6,
      name: "Recliner Chair",
      description: "Comfortable recliner chair for relaxing.",
      quantity: "10",
      location: "Chicago, USA",
      image: "https://cdn.shopify.com/s/files/1/0705/9849/2464/files/Eureka_Ergonomic_Grayson_Power_Recliner_Chair_Rocking_Swivel_with_Storage.jpg?v=1721737265",
      price: "299.99",
      category: "furniture",
    },
    {
      id: 7,
      name: "Bookshelf",
      description: "Spacious bookshelf to organize your books and items.",
      quantity: "35",
      location: "Dallas, USA",
      image: "https://www.worldmarket.com/dw/image/v2/BJWT_PRD/on/demandware.static/-/Sites-wm-master-catalog/default/dwe4c872d0/images/large/25117_XXX_v2.jpg?sw=768&sh=768&sm=fit&sfrm=tif&q=80",
      price: "89.99",
      category: "furniture",
    },
    {
      id: 8,
      name: "Dining Set",
      description: "Elegant dining set for a family of six.",
      quantity: "5",
      location: "Houston, USA",
      image: "https://www.snydersfurniture.com/cdn/shop/files/amish-48-walnut-tampa-round-dining-set-with-4-chairs-558040_grande.jpg?v=1712113768",
      price: "499.99",
      category: "furniture",
    },
  
    // Clothing
    {
      id: 9,
      name: "Men's Jacket",
      description: "Stylish jacket for men, perfect for winter.",
      quantity: "40",
      location: "Boston, USA",
      image: "https://www.stormtechusa.com/cdn/shop/products/AFP-2_FRONT_HOOD_UP_Navy_Graphite.jpg?v=1687455870&width=1200",
      price: "79.99",
      category: "clothing",
    },
    {
      id: 10,
      name: "Women's Dress",
      description: "Elegant dress for women, suitable for any occasion.",
      quantity: "60",
      location: "Miami, USA",
      image: "https://n.nordstrommedia.com/it/3a5ce757-cc97-4078-96e1-bf35f4e55def.jpeg?h=365&w=240&dpr=2",
      price: "59.99",
      category: "clothing",
    },
    {
      id: 11,
      name: "Kids' T-Shirts",
      description: "Colorful and comfortable T-shirts for kids.",
      quantity: "100",
      location: "Phoenix, USA",
      image: "https://www.beyondsome.co.uk/images/Rainbow-tshirt-main-image-179885-2.jpg",
      price: "19.99",
      category: "clothing",
    },
    {
      id: 12,
      name: "Winter Coat",
      description: "Warm and cozy winter coat for cold weather.",
      quantity: "25",
      location: "Denver, USA",
      image: "https://m.media-amazon.com/images/I/51uSRXgsjZL._AC_SX466_.jpg",
      price: "99.99",
      category: "clothing",
    },
  
    // Vehicles
    {
      id: 13,
      name: "Mountain Bike",
      description: "Durable mountain bike for adventurous trails.",
      quantity: "15",
      location: "Portland, USA",
      image: "https://marketplacer.imgix.net/gE/rIxZ5HR4G3lgZINUv1ApapoTw.png?auto=format&fm=pjpg&fit=max&s=db6d83f87a7f86297cb7317489149022",
      price: "599.99",
      category: "vehicles",
    },
    {
      id: 14,
      name: "Electric Scooter",
      description: "Eco-friendly electric scooter for daily commutes.",
      quantity: "20",
      location: "San Diego, USA",
      image: "https://gyroor.com/cdn/shop/products/GyroorH30kidselectricscooterblack-min.jpg?v=1662029381&width=1080",
      price: "299.99",
      category: "vehicles",
    },
    {
      id: 15,
      name: "Car Roof Box",
      description: "Spacious roof box for additional car storage.",
      quantity: "10",
      location: "Atlanta, USA",
      image: "https://gtspirit.com/wp-content/uploads/2023/10/GTspirit-GT3RS-Roofbox-2.jpg",
      price: "199.99",
      category: "vehicles",
    },
    {
      id: 16,
      name: "Motorcycle Helmet",
      description: "Protective and stylish helmet for motorcycle riders.",
      quantity: "50",
      location: "Las Vegas, USA",
      image: "https://new-bucket-txp.s3.amazonaws.com/v/vspfiles/photos/Full-Face-Motorcycle-15.jpg",
      price: "89.99",
      category: "vehicles",
    },
  
    // Toys and Games
    {
      id: 17,
      name: "Lego Set",
      description: "Creative building set for kids and adults.",
      quantity: "30",
      location: "Orlando, USA",
      image: "https://target.scene7.com/is/image/Target/GUEST_46141747-4c65-4bef-b086-4b72ea37d4e1?wid=488&hei=488&fmt=pjpeg",
      price: "49.99",
      category: "toys-and-games",
    },
    {
      id: 18,
      name: "Action Figures",
      description: "Detailed action figures for collectors and kids.",
      quantity: "40",
      location: "Nashville, USA",
      image: "https://i5.walmartimages.com/seo/Marvel-Ultimate-Protectors-Figure-8-Pack_6e3da6e3-f1cb-4c7f-9205-dc6adb6e2536.1ff40a57325599a71594ae9568438462.jpeg",
      price: "24.99",
      category: "toys-and-games",
    },
    {
      id: 19,
      name: "Board Game",
      description: "Fun and interactive board game for family nights.",
      quantity: "25",
      location: "Minneapolis, USA",
      image: "https://m.media-amazon.com/images/I/813J0DBqCTL.jpg",
      price: "29.99",
      category: "toys-and-games",
    },
    {
      id: 20,
      name: "Remote-Control Car",
      description: "Fast and fun remote-control car for all ages.",
      quantity: "20",
      location: "Salt Lake City, USA",
      image: "https://i5.walmartimages.com/seo/Best-Choice-Products-1-24-Officially-Licensed-RC-Lamborghini-Veneno-Sport-Racing-Car-w-2-4GHz-Remote-Control-Lime-Green_04f7dbc8-bdc4-4571-91b8-b78b5e96fa07.45c65cb328789eead43ea20ebf042e49.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
      price: "39.99",
      category: "toys-and-games",
    },
  
    // Home Goods
    {
      id: 21,
      name: "Kitchen Mixer",
      description: "Powerful kitchen mixer for baking and cooking.",
      quantity: "10",
      location: "Philadelphia, USA",
      image: "https://i01.hsncdn.com/is/image/HomeShoppingNetwork/rocs1200/kitchenaid-5-quart-stand-mixer-with-glass-bowl-and-flex-d-20230927142614783~848658_alt1.jpg",
      price: "149.99",
      category: "home-goods",
    },
    {
      id: 22,
      name: "Vacuum Cleaner",
      description: "Efficient vacuum cleaner for spotless cleaning.",
      quantity: "15",
      location: "Detroit, USA",
      image: "https://us.eureka.com/cdn/shop/files/cq5dam.web.5000.5000_8_64701121-b15e-4048-ae7e-eb78d7dec18b_1_500x.jpg?v=1717738013",
      price: "99.99",
      category: "home-goods",
    },
    {
      id: 23,
      name: "Air Purifier",
      description: "High-performance air purifier for clean air.",
      quantity: "12",
      location: "Baltimore, USA",
      image: "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/hero/497044-01.png?$responsive$&cropPathE=mobile&fit=stretch,1&wid=640",
      price: "199.99",
      category: "home-goods",
    },
    {
      id: 24,
      name: "Coffee Maker",
      description: "Advanced coffee maker for a perfect brew.",
      quantity: "18",
      location: "Cleveland, USA",
      image: "https://m.media-amazon.com/images/I/71uLuTiXQlL._AC_UF894,1000_QL80_.jpg",
      price: "79.99",
      category: "home-goods",
    },
  ];
  